services:
  ui:
    build: 
      context: .
      target: development
    ports:
      - 3000:3000
      - 3002:3002
    volumes:
      - ./src:/app/src
    # environment:
      # - VITE_API_URL=http://localhost:3001
    networks:
      - ebytr-dev

networks:
  ebytr-dev:
    name: ebytr-dev
